on:
  push
jobs:
  test:
    name: actions when push
    runs-on: self-hosted

    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js 14
      uses: actions/setup-node@v1
      with:
        node-version: 16.14

    - name: npm install, build and test
      run: |
        npm install
        npm install -g pm2
        pm2 start server.js
        pm2 delete all
        pm2 start server.js
